# pnpm workspace configuration

packages:
  # Root package (main CLI)
  - '.'
  # Core package (domain, application, infrastructure layers)
  - 'packages/core'
  # Web UI package
  - 'src/presentation/web'
