/**
 * Spec Initializer Service
 *
 * Creates feature specification directories with YAML template files.
 * Templates match exactly what /shep-kit:new-feature produces,
 * enabling dogfooding — the CLI and the skill use the same spec format.
 */

import { mkdir, readdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type {
  ISpecInitializerService,
  SpecInitializerOptions,
  SpecInitializerResult,
} from '@/application/ports/output/services/spec-initializer.interface.js';
import { computeRepoHash } from '@/infrastructure/services/filesystem/repo-hash.js';
import { getShepHomeDir } from '@/infrastructure/services/filesystem/shep-directory.service.js';

/**
 * Pad a number to 3 digits with leading zeros.
 */
function padNumber(n: number): string {
  return String(n).padStart(3, '0');
}

/**
 * Apply template variable substitution matching init-feature.sh behavior.
 * Handles both {{VAR}} and { { VAR } } (Prettier-formatted) patterns.
 */
function applyTemplate(
  template: string,
  vars: {
    nnn: string;
    slug: string;
    featureNumber: number;
    date: string;
    timestamp: string;
    description: string;
  }
): string {
  const replacements: [RegExp, string][] = [
    [/\{\{ ?NNN ?\}\}|\{ \{ NNN \} \}/g, vars.nnn],
    [/\{\{ ?FEATURE_NAME ?\}\}|\{ \{ FEATURE_NAME \} \}/g, vars.slug],
    [/\{\{ ?FEATURE_ID ?\}\}|\{ \{ FEATURE_ID \} \}/g, `${vars.nnn}-${vars.slug}`],
    [/\{\{ ?FEATURE_NUMBER ?\}\}|\{ \{ FEATURE_NUMBER \} \}/g, String(vars.featureNumber)],
    [/\{\{ ?BRANCH_NAME ?\}\}|\{ \{ BRANCH_NAME \} \}/g, `feat/${vars.nnn}-${vars.slug}`],
    [/\{\{ ?DATE ?\}\}|\{ \{ DATE \} \}/g, vars.date],
    [/\{\{ ?TIMESTAMP ?\}\}|\{ \{ TIMESTAMP \} \}/g, vars.timestamp],
    [/\{\{ ?DESCRIPTION ?\}\}|\{ \{ DESCRIPTION \} \}/g, vars.description],
  ];

  let result = template;
  for (const [pattern, replacement] of replacements) {
    result = result.replace(pattern, replacement);
  }
  return result;
}

// ─── YAML Templates ────────────────────────────────────────────────
// These match .claude/skills/shep-kit-new-feature/templates/ exactly.

const SPEC_YAML = `# Feature Specification (YAML)
# This is the source of truth. Markdown is auto-generated from this file.

name: {{FEATURE_NAME}}
number: {{NNN}}
branch: feat/{{NNN}}-{{FEATURE_NAME}}
oneLiner: {{DESCRIPTION}}
userQuery: >
  {{DESCRIPTION}}
summary: >
  {{DESCRIPTION}}
phase: Analysis
sizeEstimate: M

# Relationships
relatedFeatures:
  []

technologies:
  []

relatedLinks:
  []

# Open questions (must be resolved before implementation)
openQuestions:
  []

# Markdown content (the actual spec)
content: |
  ## Problem Statement

  {{DESCRIPTION}}

  ## Success Criteria

  - [ ] TBD

  ## Affected Areas

  | Area | Impact | Reasoning |
  | ---- | ------ | --------- |
  | TBD  | TBD    | TBD       |

  ## Dependencies

  None identified.

  ## Size Estimate

  **M** - To be refined during research

  ---

  _Generated by feature agent — proceed with research_
`;

const RESEARCH_YAML = `# Research Artifact (YAML)
# This is the source of truth. Markdown is auto-generated from this file.

name: {{FEATURE_NAME}}
summary: Technical analysis for {{NNN}}-{{FEATURE_NAME}}

# Relationships
relatedFeatures: []
technologies: []
relatedLinks: []

# Structured technology decisions
decisions: []

# Open questions (should be resolved by end of research)
openQuestions: []

# Markdown content (the full research document)
content: |
  ## Status

  - **Phase:** Research
  - **Updated:** {{DATE}}

  ## Technology Decisions

  TBD

  ---

  _To be updated during research phase_
`;

const PLAN_YAML = `# Implementation Plan (YAML)
# This is the source of truth. Markdown is auto-generated from this file.

name: {{FEATURE_NAME}}
summary: Implementation plan for {{NNN}}-{{FEATURE_NAME}}

# Relationships
relatedFeatures: []
technologies: []
relatedLinks: []

# Structured implementation phases
phases: []

# File change tracking
filesToCreate: []
filesToModify: []

# Open questions (should all be resolved before implementation)
openQuestions: []

# Markdown content (the full plan document)
content: |
  ## Status

  - **Phase:** Planning
  - **Updated:** {{DATE}}

  ## Implementation Strategy

  TBD

  ---

  _To be updated during planning phase_
`;

const TASKS_YAML = `# Task Breakdown (YAML)
# This is the source of truth. Markdown is auto-generated from this file.

name: {{FEATURE_NAME}}
summary: Task breakdown for {{NNN}}-{{FEATURE_NAME}}

# Relationships
relatedFeatures: []
technologies: []
relatedLinks: []

# Structured task list
tasks: []

# Total effort estimate
totalEstimate: TBD

# Open questions
openQuestions: []

# Markdown content (the full tasks document)
content: |
  ## Status

  - **Phase:** Implementation
  - **Updated:** {{DATE}}

  ## Task List

  TBD

  ---

  _Task breakdown for implementation tracking_
`;

const FEATURE_YAML = `feature:
  id: '{{FEATURE_ID}}'
  name: '{{FEATURE_NAME}}'
  number: {{FEATURE_NUMBER}}
  branch: '{{BRANCH_NAME}}'
  lifecycle: 'research'
  createdAt: '{{TIMESTAMP}}'

status:
  phase: 'research'
  progress:
    completed: 0
    total: 0
    percentage: 0
  currentTask: null
  lastUpdated: '{{TIMESTAMP}}'
  lastUpdatedBy: 'feature-agent'

validation:
  lastRun: null
  gatesPassed: []
  autoFixesApplied: []

tasks:
  current: null
  blocked: []
  failed: []

checkpoints:
  - phase: 'feature-created'
    completedAt: '{{TIMESTAMP}}'
    completedBy: 'feature-agent'

errors:
  current: null
  history: []
`;

const TEMPLATES: { filename: string; content: string }[] = [
  { filename: 'spec.yaml', content: SPEC_YAML },
  { filename: 'research.yaml', content: RESEARCH_YAML },
  { filename: 'plan.yaml', content: PLAN_YAML },
  { filename: 'tasks.yaml', content: TASKS_YAML },
  { filename: 'feature.yaml', content: FEATURE_YAML },
];

export class SpecInitializerService implements ISpecInitializerService {
  async initialize(
    basePath: string,
    slug: string,
    featureNumber: number,
    description: string,
    mode?: 'fast',
    options?: SpecInitializerOptions
  ): Promise<SpecInitializerResult> {
    const storageMode = options?.storageMode ?? 'in-repo';

    // Scan existing spec directories for highest NNN prefix to avoid collisions
    // (specs may have been created outside the DB, e.g., via /shep-kit:new-feature)
    const resolvedNumber = await this.resolveNextNumber(
      basePath,
      featureNumber,
      options?.repositoryPath
    );

    const nnn = padNumber(resolvedNumber);
    const specDirName = `${nnn}-${slug}`;
    const specDir = this.computeSpecDir(
      basePath,
      specDirName,
      storageMode,
      options?.repositoryPath
    );

    // Create the spec directory
    await mkdir(specDir, { recursive: true });

    const now = new Date();
    const date = now.toISOString().split('T')[0];
    const timestamp = now.toISOString().replace(/\.\d{3}Z$/, 'Z');

    const vars = { nnn, slug, featureNumber: resolvedNumber, date, timestamp, description };

    // In fast mode, write feature.yaml + spec.yaml (spec.yaml stores the user query
    // which the fast-implement node reads; no research/plan/tasks needed)
    const templates =
      mode === 'fast'
        ? TEMPLATES.filter(
            ({ filename }) => filename === 'feature.yaml' || filename === 'spec.yaml'
          )
        : TEMPLATES;

    // Write template files
    await Promise.all(
      templates.map(({ filename, content }) =>
        writeFile(join(specDir, filename), applyTemplate(content, vars), 'utf-8')
      )
    );

    return { specDir, featureNumber: nnn };
  }

  /**
   * Compute the spec directory path based on storage mode.
   */
  private computeSpecDir(
    basePath: string,
    specDirName: string,
    storageMode: 'in-repo' | 'shep-managed',
    repositoryPath?: string
  ): string {
    if (storageMode === 'shep-managed') {
      if (!repositoryPath) {
        throw new Error('repositoryPath is required when storageMode is shep-managed');
      }
      const repoHash = computeRepoHash(repositoryPath);
      return join(getShepHomeDir(), 'repos', repoHash, 'specs', specDirName);
    }
    return join(basePath, '.shep', 'specs', specDirName);
  }

  /**
   * Scan spec directories for existing NNN-* entries and return the next available number.
   * Scans up to 3 locations to prevent collisions during the transition period:
   * 1. specs/ (legacy location)
   * 2. .shep/specs/ (new in-repo location)
   * 3. ~/.shep/repos/<hash>/specs/ (shep-managed location, when repositoryPath provided)
   *
   * Uses the DB-derived hint as a minimum, but always respects filesystem state.
   */
  private async resolveNextNumber(
    basePath: string,
    hint: number,
    repositoryPath?: string
  ): Promise<number> {
    const dirsToScan = [join(basePath, 'specs'), join(basePath, '.shep', 'specs')];

    if (repositoryPath) {
      const repoHash = computeRepoHash(repositoryPath);
      dirsToScan.push(join(getShepHomeDir(), 'repos', repoHash, 'specs'));
    }

    let maxExisting = 0;
    for (const dir of dirsToScan) {
      const max = await this.scanDirForMaxNumber(dir);
      maxExisting = Math.max(maxExisting, max);
    }

    return Math.max(maxExisting + 1, hint);
  }

  /**
   * Scan a single directory for NNN-* prefixed entries and return the max number found.
   * Returns 0 if the directory does not exist or is empty.
   */
  private async scanDirForMaxNumber(dirPath: string): Promise<number> {
    let entries: string[];
    try {
      entries = await readdir(dirPath);
    } catch {
      return 0;
    }

    let max = 0;
    for (const entry of entries) {
      const match = entry.match(/^(\d{3})-/);
      if (match) {
        max = Math.max(max, parseInt(match[1], 10));
      }
    }
    return max;
  }
}
